transcodestersite:
    type: rest
    resource: @PortalBundle/Controller/TranscoDestTerrSiteController.php

transconatureope:
    type: rest
    resource: @PortalBundle/Controller/TranscoNatureOpeController.php

soap:
    resource: PortalBundle\Controller\SoapServerController