services:
    portal_authenticator:
        class:  PortalBundle\Security\PortalAuthenticator
        public: false

    portal.request_filter_listener:
        class: PortalBundle\Listener\RequestFilterListener
        arguments: [ @security.token_storage ]
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    security.region_voter:
            class: PortalBundle\Voter\RegionVoter
            tags:
                - { name: security.voter }
            public: false

    security.role_voter:
            class: PortalBundle\Voter\RoleVoter
            tags:
                - { name: security.voter }
            public: false

    security.agency_voter:
            class: PortalBundle\Voter\AgencyVoter
            tags:
                - { name: security.voter }
            public: false
