services:
#Authentication
    portal_authenticator:
        class:  PortalBundle\Security\PortalAuthenticator
        public: false

#Voters
    security.region_voter:
            class: PortalBundle\Voter\RegionVoter
            tags:
                - { name: security.voter }
            public: false

    security.role_voter:
            class: PortalBundle\Voter\RoleVoter
            tags:
                - { name: security.voter }
            public: false

    security.agency_voter:
            class: PortalBundle\Voter\AgencyVoter
            tags:
                - { name: security.voter }
            public: false

#Repositories
    portal.region_repository:
            class:  PortalBundle\Repository\RegionRepository
            factory: ["@doctrine.orm.entity_manager", getRepository]
            arguments:
                - "PortalBundle:Region"
            public: true

    portal.agency_repository:
            class:  PortalBundle\Repository\AgencyRepository
            factory: ["@doctrine.orm.entity_manager", getRepository]
            arguments:
                - "PortalBundle:Agency"
            public: true