imports:
    - { resource: config.yml }
    - { resource: parameters_recette.yml }
    - { resource: gdi_urls_recette.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: false
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  debug
        console:
            type:   console
            bubble: false
            verbosity_levels:
                VERBOSITY_VERBOSE: INFO
                VERBOSITY_VERY_VERBOSE: DEBUG
            channels: ["!doctrine"]
        console_very_verbose:
            type:   console
            bubble: false
            verbosity_levels:
                VERBOSITY_VERBOSE: NOTICE
                VERBOSITY_VERY_VERBOSE: NOTICE
                VERBOSITY_DEBUG: DEBUG
            channels: ["doctrine"]

security:
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)
            security: false
        saml:
            pattern: ^/
            aerial_ship_saml_sp:
                local_logout_path: /logout
                default_target_path: /
                create_user_if_not_exists: false
                provider: fos_userbundle
                services:
                    saml:
                        idp:
                            file: "@UserBundle/Resources/FedId/dev/GIDPD_FederationMetaData_20151028.xml"
                        sp:
                            config:
                                base_url: https://portail-gdi-rec.carma.grdf.fr/api
                                entity_id: https://portail-gdi-rec.carma.grdf.fr/api
                            meta:
                                binding:
                                    authn_request: post
            logout:
                path: /logout
        main:
            anonymous: ~


