NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc

portal:
    type: rest
    prefix: /
    resource: "@PortalBundle/Resources/config/routing.yml"
