portal:
    type: rest
    resource: "@PortalBundle/Resources/config/routing.yml"
    prefix:   /

NelmioApiDocBundle:
    prefix:   /doc
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
