user:
    type: rest
    prefix: /portal
    resource: "@UserBundle/Resources/config/routing.yml"

portal:
    type: rest
    resource: "@PortalBundle/Resources/config/routing.yml"

NelmioApiDocBundle:
    prefix:   /doc
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"

aerialship_saml_sp_bundle:
    resource: "@AerialShipSamlSPBundle/Resources/config/routing.yml"

