# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
      PortalBundle\Entity\User: sha512

    providers:
        portail_user_provider:
            entity: {class: PortalBundle\Entity\User}

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        saml:
            pattern: ^/
            aerial_ship_saml_sp:
                local_logout_path: /logout
                default_target_path: /
                create_user_if_not_exists: false
                provider: fos_userbundle
                services:
                    saml:
                        idp:
                            file: "@PortalBundle/Resources/FedId/dev/GIDPD_FederationMetaData_20151028.xml"
                        sp:
                            config:
                                base_url: https://portail-gdi-rec.carma.grdf.fr
                                entity_id: https://portail-gdi-rec.carma.grdf.fr
            logout:
                path: /logout

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
