# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
      UserBundle\Entity\User: sha2

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    role_hierarchy:
        ROLE_VISITEUR                : ROLE_USER
        ROLE_TECHNICIEN              : ROLE_VISITEUR
        ROLE_PROGRAMMATEUR           : ROLE_TECHNICIEN
        ROLE_PROGRAMMATEUR_AVANCE    : ROLE_TECHNICIEN
        ROLE_MANAGER_APPO            : ROLE_TECHNICIEN
        ROLE_REFERENT_EQUIPE         : ROLE_TECHNICIEN
        ROLE_MANAGER_ATG             : ROLE_TECHNICIEN
        ROLE_ADMINISTRATEUR_LOCAL    : ROLE_TECHNICIEN
        ROLE_ADMINISTRATEUR_NATIONAL : [ROLE_ADMINISTRATEUR_LOCAL]
        ROLE_ADMINISTRATEUR_SI       : [ROLE_ADMINISTRATEUR_NATIONAL, ROLE_ALLOWED_TO_SWITCH]

    access_control:
        - { path: ^/doc , roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profiles , roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/ , roles: ROLE_VISITEUR }


