parameters:
    wsdl_exposed_path : "%kernel.root_dir%/Resources/wsdl/exposed"
    wsdl_login    : PortailGDI
    wsdl_password : PortailGDI
    exposed_wsdls:
        serviceTransco :
            filePath : "%wsdl_exposed_path%/serviceTransco/com.grdf.serviceTranscoGDI.v1.1.wsdl"
            location: 'http://10.0.55.2:8091/app_dev.php/soap/service-transco'