transcoagence:
    type: rest
    resource: @TranscoBundle/Controller/TranscoAgenceController.php

transcodisco:
    type: rest
    resource: @TranscoBundle/Controller/TranscoDiscoController.php

transcogmao:
    type: rest
    resource: @TranscoBundle/Controller/TranscoGmaoController.php

transcoOptic:
    type: rest
    resource: @TranscoBundle/Controller/TranscoOpticController.php

soap:
    resource: TranscoBundle\Controller\SoapServerController
