UserBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: { fields: username, message: "Ce GAIA est déjà attribué à un utilisateur" }
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: { fields: nni, message: "Ce NNI est déjà attribué à un utilisateur" }
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: { fields: email, message: "Cet EMAIL est déjà attribué à un utilisateur" }
    properties:
          firstName:
              - NotNull:
                  message: "Le prénom est obligatoire"
              - Length:
                  max: 40
                  maxMessage: "Le prénom est trop long"
          lastName:
              - NotNull:
                  message: "Le nom est obligatoire"
              - Length:
                  max: 40
                  maxMessage: "Le nom est trop long"
          entity:
              - NotNull:
                  message: "L'entité est obligatoire"
          username:
              - NotNull:
                  message: "Le GAIA est obligatoire"
              - Length:
                  max: 6
                  maxMessage: "Le GAIA est trop long"
          email:
              - Email:
                  message: "Le format de l'email n'est pas valide"
              - Length:
                  max: 90
                  maxMessage: "L'email est trop long"
          nni:
              - Length:
                  max: 8
                  maxMessage: "Le NNI est trop long"
          phone1:
              - Length:
                  max: 10
                  maxMessage: "Le Téléphone 1 est trop long"
          phone2:
              - Length:
                  max: 10
                  maxMessage: "Le Téléphone 2 est trop long"